# Generated by Django 6.0.3 on 2026-03-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=10, null=True),
        ),
    ]
