# Generated by Django 6.0.3 on 2026-04-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=9800000001, max_length=15),
            preserve_default=False,
        ),
    ]
